src/Domain/Entity/EntityInterface.php
<?php

namespace App\Domain\Entity;

interface EntityInterface
{
    public function getId(): int;
}

templates/layout.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    {# Run `composer require symfony/webpack-encore-bundle`
            and uncomment the following Encore helpers to start using Symfony UX #}
    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}
    {% endblock %}
</head>
<body>
{% block body %}{% endblock %}
{% block footer %}{% endblock %}
</body>
</html>

templates/macros.twig
{% macro user_table_body(users) %}
  {% for user in users %}
    <tr>
      <td>{{ user.id|my_twice }}</td>
      <td>{{ user.login }}</td>
      <td>
        <ul>
          {% for role in user.roles %}
            <li>{{ role }}</li>
          {% endfor %}
        </ul>
      </td>
      <td>{{ user.communicationChannel }}</td>
      <td>({{ user.communicationMethod }})</td>
    </tr>
  {% endfor %}
{% endmacro %}

templates/phone-user.twig
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  {% block head_css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/1.1.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  {% endblock %}
</head>
<body>
{% form_theme form 'bootstrap_4_layout.html.twig' %}
<div style="width:50%;margin-left:10px;margin-top:10px">
  {{ form(form) }}
</div>
{% block head_js %}
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
{% endblock %}
</body>
</html>

templates/user-list.twig
{% extends 'layout.twig' %}

 {% block title %}
   User list
 {% endblock %}
 {% block body %}
   <ol id="user.list">
     {% for user in users %}
       <li>{{ user.id }}. {{ user.login|lower }} {{ user.communicationChannel|upper }} ({{ user.communicationMethod }}) </li>
     {% endfor %}
   </ol>
 {% endblock %}
 {% block footer %}
   <h1>Footer</h1>
   {{ block('body') }}
   <h1>Repeat twice</h1>
   {{ block('body') }}
 {% endblock %}

templates/user-table.twig
{% extends 'layout.twig' %}

 {% import 'macros.twig' as macros %}

 {% block title %}
     {{ my_greet('User') }}
 {% endblock %}
 {% block body %}
     <table class="table table-hover">
         <tbody>
         <tr><th>ID</th><th>Логин</th><th>Роли</th><th>Канал коммуникации</th><th>Адрес</th></tr>
         {{ macros.user_table_body(users) }}
         </tbody>
     </table>
 {% endblock %}